// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvmSbQXLr7N0gSjPvuYH7j0HwY-iGsluI',
    appId: '1:358797690055:web:934eb84c6862aabd426ae2',
    messagingSenderId: '358797690055',
    projectId: 'skill-loop-app',
    authDomain: 'skill-loop-app.firebaseapp.com',
    storageBucket: 'skill-loop-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbkMTSujvjrxkY-CTyLWEKaiJN-Iktcv4',
    appId: '1:358797690055:android:884efb97ac149bb5426ae2',
    messagingSenderId: '358797690055',
    projectId: 'skill-loop-app',
    storageBucket: 'skill-loop-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDL1Te2BKR_tWhHhHeACbTEvsX7K87zCWE',
    appId: '1:358797690055:ios:f8690af0ed8af58c426ae2',
    messagingSenderId: '358797690055',
    projectId: 'skill-loop-app',
    storageBucket: 'skill-loop-app.firebasestorage.app',
    iosBundleId: 'com.example.skillLoop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDL1Te2BKR_tWhHhHeACbTEvsX7K87zCWE',
    appId: '1:358797690055:ios:f8690af0ed8af58c426ae2',
    messagingSenderId: '358797690055',
    projectId: 'skill-loop-app',
    storageBucket: 'skill-loop-app.firebasestorage.app',
    iosBundleId: 'com.example.skillLoop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvmSbQXLr7N0gSjPvuYH7j0HwY-iGsluI',
    appId: '1:358797690055:web:e9c9a0053afeff7b426ae2',
    messagingSenderId: '358797690055',
    projectId: 'skill-loop-app',
    authDomain: 'skill-loop-app.firebaseapp.com',
    storageBucket: 'skill-loop-app.firebasestorage.app',
  );
}
